# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 771e54888204793f5afbd6c8710c0890efce4593
#Authorization: Token 51bc463165cd1a4664e1ec7ffa9680dc85690075
#Authorization: Token c9043f94295ee410715ab7063f81629468b53e2e

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token a8bf7d836a16d15b4a13a0c2ab0ce4f270d55ab0

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

# удаление
DELETE {{baseUrl}}/advertisements/3/
Authorization: Token c9043f94295ee410715ab7063f81629468b53e2e
#Authorization: Token 771e54888204793f5afbd6c8710c0890efce4593
